# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=255, unique=True)),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('is_staff', models.BooleanField()),
                ('is_superuser', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
